name: Hello_world1
on:
  push:
    branches:
      - main
jobs:
  First-hello-world-job:
   runs-on: ubuntu-latest
   steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Print message
        run: echo "hello world git action testing"
  run-python:
   runs-on: ubuntu-latest
   steps:
       - name: checkout code
         uses: actions/checkout@v3
       - name: Setup python
         uses: action/checkout@v3
         with:
           python-version: 3.9
       - name: Install dependency
         run: |
           python -m pip install --upgrade pip
           pip install pytest
       - name: Run testcases
         run: pytest
        
         
       
  
       
       

  
